### ISSUE TITLE
node_modules/websocket: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by petermetz** [hyperledger-labs/blockchain-integration-framework#25]
When you follow the `simple-asset-transfer` example, starting the fabric DLT fails with the issue below.

Problem doesn't always manifest.

Workaround
-------------

Delete the .git directory of the problematic node module
```sh
rm -rf examples/simple-asset-transfer/node_modules/websocket/.git/
```

Solution Ideas
----------

- Maybe it fixes itself when we up the NodeJS version requirements (so new npm version) from forcing 8.x to 10.x, needs testing.

Crash log
----------
```sh
$ npm run fabric

> @hyperledger/blockchain-integration-framework.examples.simple-asset-transfer@0.1.0 fabric /home/redactedusername/a/blockchain/blockchain-integration-framework/examples/simple-asset-transfer
> cd fabric/scripts && ./start.sh


Stopping peer1.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping peer1.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping ca_peerOrg1            ... done
Stopping ca_peerOrg2            ... done
Stopping orderer.example.com    ... done
Removing peer1.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing peer1.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca_peerOrg1            ... done
Removing ca_peerOrg2            ... done
Removing orderer.example.com    ... done
Removing network artifacts_default

========== No containers available for deletion ==========


========== No images available for deletion ===========

Creating network "artifacts_default" with the default driver
Creating orderer.example.com ... done
Creating ca_peerOrg1            ... done
Creating ca_peerOrg2            ... done
Creating peer0.org2.example.com ... done
Creating peer0.org1.example.com ... done
Creating peer1.org2.example.com ... done
Creating peer1.org1.example.com ... done


============== Installing node modules =============
npm ERR! path /home/redactedusername/a/blockchain/blockchain-integration-framework/examples/simple-asset-transfer/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /home/redactedusername/a/blockchain/blockchain-integration-framework/examples/simple-asset-transfer/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /home/redactedusername/a/blockchain/blockchain-integration-framework/examples/simple-asset-transfer/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/redactedusername/.npm/_logs/2019-11-05T19_50_11_296Z-debug.log

Starting the SDK server ... /home/redactedusername/a/blockchain/blockchain-integration-framework/examples/simple-asset-transfer/fabric/scripts
23015
Initializing the network ...
[2019-11-05T11:50:22.757] [ERROR] init-network - Error: failed TypeError: Cannot read property 'curve' of undefined
    at enroll (/home/redactedusername/a/blockchain/blockchain-integration-framework/examples/simple-asset-transfer/fabric/scripts/init-network.js:24:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger/blockchain-integration-framework.examples.simple-asset-transfer@0.1.0 fabric: `cd fabric/scripts && ./start.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hyperledger/blockchain-integration-framework.examples.simple-asset-transfer@0.1.0 fabric script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/redactedusername/.npm/_logs/2019-11-05T19_50_22_771Z-debug.log
```

**Comment by petermetz** [comment]
Fixed implicitly with Web3 upgrade (most likely).
